language: node_js
node_js:
- node
services:
- mongodb
env:
- PATHWAYS_MONGO_HOST=localhost PATHWAYS_MONGO_PORT=27017 PATHWAYS_MONGO_DB=bc211
install:
- npm install
before_script:
- wget https://github.com/pg-irc/sample-data/archive/master.zip -O sample_data.zip;
  unzip sample_data.zip; cd data; node seed_211.js ../sample-data-master/simple testing;
  cd ..;
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: RrWhbXx89T4tshuHG2Epp2a4KUP5sRgoRoATCl0rUl+Q+8TW4yLAfHXxCZS28by2NLRCAQt2DUT5RUK9Pr7nDwe4RXLsTBk857Y/xSuGefMSuopZnWxx0ALf+gAlqNwnT6icVvdqBmzRi0lg+PI2PB06io5ELxLX1lT9U9q/XB7afuV3V6CJ3wqIfKH13H1CxorzFiCz3bYCRlY111HbKnhL6NMorVUadXuVeTEj1rbWkgIsGX1jXrou/uZgwLL+z8OGMk08a1Aga1e3+gfpkiJkael2SAHezWkGJslZiS0marRle2j/c4jZh/56qHHJQeDLwSnWQi/Dqc6oqWFwaOdNjWOtjO8WNKSYpU40mtb89rLLGuxSfZRd7H3CW65S/sZ7/+tv/6+7VM3zaNlQapRAoI88QYpjAjmTEHYI1lgTFTSlYlHPl5C7MuKOQM7jGGBceEBLBJmQHKnTQ6ZP/Jynowa6iA7JfDI6+Grf7lB3Uj13T5XbsNzxh820ubPC5tJ9LXlf21n75UfbhWHl72IbP5FSH4bjcVzFSl47pPgDXT9yzAHJxTQsd1L96Y+uLl0oMQivuCdl7T9BjsMRoZp4ROv4thyL3lrXG+IYeBbWFFCybED7bIp9gevSDlbBvXxhTlIb26H2ceSKv17n5JDhhUdN3uiXmf7v1KANPhE=
  app: pathways-backend
  on:
    repo: pg-irc/pathways-backend
notifications:
  slack: peacegeeks:5vsKNY6nV4sqnQ71uoSkPlxD
