language: node_js
node_js:
- node
services:
- mongodb
env:
- PATHWAYS_MONGO_HOST=localhost PATHWAYS_MONGO_PORT=27017 PATHWAYS_MONGO_DB=bc211
install:
- npm install
before_script:
- wget https://github.com/pg-irc/sample-data/archive/master.zip -O sample_data.zip;
  unzip sample_data.zip; cd data; node seed_211.js ../sample-data-master/simple testing;
  cd ..;
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: CCb+14kKXaqHLh8Fj7vwFyb2snP4O9e7fDI92k/VIwzYlOciiyc+L+KfFaO67uX1rr4u+jFXSyLB4YwevQ1FLU6P3U/ujUiqhwc8bu2pEzFRwC0nxrpCRsvY2Chm3ZUYsUfL2j/40nN0MxlpPGdHpmmgZAYklV4Vqx6uKbMJqQWSRSlEGdgdYHpwkksWnx7uuIRJbrmTRD0z1t+H6HDAxMQFeW4oRLgS6ZYxhZvMVQT7Q7D7rACHxIR+dBGNrzsSzN1cEc1G+BTBp/s4foCIxwSpvEtUiFB410c1YMiLkHs8mKJk7CUv1TtgoAlRe+DltWfZ5tLGDyaW2M0MWdy7QNXyEvyGpC0HvGvAtX0or5kl5DXMnR2eG3uXIkoRIt+f9Zu37QBU6nUzcRuFmDWgvZ8tyiD1QZse4wUeXJZPybIc0WeAJUUk1/5XUrr5julW/eB8HGBBDJilp0h9EhYasStFRtdZmG+7Ou9Vvg0nDrv06UYLc9IoX1IzbjxWWNC2UMfqEfKdW+wrsrOA7KctBlDogcPKmfB46H9QlGEdZ34ezSmhNTcbjvqGklHHrCbGfAr/K1UI023bKDUKlxcvgZd/e5gCVRSGFbCcB92z9RMM/6q8VBF+rRf/O4JS7GAeVqT11bvYVZ0CTUbEyuZcej3lQR1jMx2w1h/PkILbkhs=
  app: pathways-backend
  on:
    repo: pg-irc/pathways-backend
notifications:
  slack: peacegeeks:5vsKNY6nV4sqnQ71uoSkPlxD
