language: node_js
node_js:
- node
services:
- mongodb
env:
- PATHWAYS_MONGO_HOST=localhost PATHWAYS_MONGO_PORT=27017 PATHWAYS_MONGO_DB=bc211
install:
- npm install
before_script:
- wget https://github.com/pg-irc/sample-data/archive/master.zip -O sample_data.zip;
  unzip sample_data.zip; cd data; node seed_211.js ../sample-data-master/simple testing;
  cd ..;
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: DNZMwp/bwxVSzNWuTK/DdMXKKwr4f1TR9SA8zPEEil8M/c4OhgOJMhkxJda00MUUs+CbfZYbwYrywQe9aryWDx5byK04twFuNNZ20xDfD/Tjl8B2R/wbf1ZTuBhh6eRYA5Nuq4z17nUD6LNOn93WLHm2cZ3FWCtRcLgwnqym+4h1UhOCRHZUj2ZNGukd4o8eKHYgM+cXIZqQHyD2aRQBrWy/t67dSgvDKsJPJu//WZViWSy69OVpjhnPZyY3hBZdc7vdTGjsTI1C6ZExws+mrGvgzyWLcgwa/VHiGGuSpXGlGVy2FiZSEx8QBr7H1Se37fT/fDUm4Dnns6c+I/rLWiI7zUVauFGVadNCmq3+BcNUPVd8Mm3iIrQfgRV+CPn7jEF6i4bip4rJZvPdytoadYRA195U5tjW0HxOD9dHEjs+WgtAig9/AVuDPq+n4QlmZsVNjdWyNUvd5fwk+Rfymynp/bM2F/dPSOk3+w5RVG2aHMI9kdczm9RLHg/rLa/ufpyEg3ZCGpEr3h+Alw2q3I9htWfdZgRVPLn9T4LXx25dP+i5mLp5kFe9jziSv8isbjMWz0jweowXPH7jMZ7W2nY6PsZaY5ftTJ9bcxS9qTybzUpvNo/oPtjBtHnkEY8CMGjQqix5UDvhEX/qnlgDe7/h7q1GRM5JoG7Z1GDNkl4=
  app: pathways-backend
  on:
    repo: pg-irc/pathways-backend
notifications:
  slack: peacegeeks:5vsKNY6nV4sqnQ71uoSkPlxD
