version: '2'
services:
  pathways-backend:
    build: .
    image: pg-irc/pathways-backend
    volumes:
      - .:/pathways-backend
    environment:
      - PATHWAYS_MONGO_HOST=pathways-mongo
      - PATHWAYS_MONGO_PORT=27017
      - PATHWAYS_MONGO_DB=bc211
    ports:
      - 3000:3000
      - 9000:9000
    links:
      - pathways-mongo
    depends_on:
      - pathways-mongo
  pathways-mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 28000:27017
